import Image from "next/image"
import { Inter } from "@next/font/google"
import Link from "next/link"

import ChildrenTitle from "@/components/children-title/page"
import { MdOutlineSettings } from "react-icons/md"

export const metadata = {
  title: "Casarão | Configurações",
  description: "Generated by Next.js",
}

export default function Settings() {
  return (
    <div className='min-h-screen'>
      <ChildrenTitle
        title='Configurações'
        iconName={<MdOutlineSettings size={54} />}
      />
    </div>
  )
}
