// "use client"

import { Logo } from "../logo/page"

import { BsOpticalAudioFill } from "react-icons/bs"
import { CiUser } from "react-icons/ci"
import { GiGuitarHead, GiDoorHandle, GiDrumKit } from "react-icons/gi"
import { IoIosMusicalNotes } from "react-icons/io"
import { HiOutlineUserGroup } from "react-icons/hi"
import { FaTheaterMasks } from "react-icons/fa"

import Link from "next/link"

export const metadata = {
  title: "mms - casarão",
  description: "Generated by Next.js",
}

export function Leftbar() {
  const menuItem = [
    { icon: <CiUser />, path: "/user", item: "Usuário" },
    { icon: <GiDoorHandle />, path: "/environment", item: "Ambiente" },
    { icon: <FaTheaterMasks />, path: "/artist", item: "Artista" },
    { icon: <GiDrumKit />, path: "/band", item: "Banda" },
    { icon: <HiOutlineUserGroup />, path: "/role", item: "Função" },
    { icon: <GiGuitarHead />, path: "/instrument", item: "Instrumento" },
    { icon: <BsOpticalAudioFill />, path: "/equipament", item: "Equipamento" },
    { icon: <IoIosMusicalNotes />, path: "/music", item: "Música" },
  ]

  return (
    <div className='w-[14rem] bg-gray-900 fixed h-screen'>
      <div className='flex flex-col justify-center p-2 items-center bg-yellow-300'>
        <Logo />
      </div>
      <div className='text-yellow-300  min-h-screen'>
        <ul>
          {menuItem.map((item, i) => {
            return (
              <div key={i} className='hover:bg-yellow-500/60 hover:text-white'>
                <Link href={item.path}>
                  <li className='flex gap-2 p-2 items-center'>
                    <span className=' text-4xl rounded p-2 bg-gray-400 bg-opacity-20 backdrop-blur-lg drop-shadow-lg'>
                      {item.icon}
                    </span>
                    {item.item}
                  </li>
                </Link>
              </div>
            )
          })}
        </ul>
      </div>
    </div>
  )
}
