// "use client"

import { Logo } from "../logo/page"

import { BsOpticalAudioFill } from "react-icons/bs"
import { CiUser } from "react-icons/ci"
import { GiGuitarHead, GiDoorHandle, GiDrumKit } from "react-icons/gi"
import { IoIosMusicalNotes } from "react-icons/io"
import { HiOutlineUserGroup } from "react-icons/hi"
import { FaTheaterMasks } from "react-icons/fa"

import Link from "next/link"

export const metadata = {
  title: "mms - casarão",
  description: "Generated by Next.js",
}

export function Leftbar() {
  const menuItem = [
    { icon: <CiUser/>, path: "/user", item: "Usuário" },
    { icon: <GiDoorHandle />, path: "/environment", item: "Ambiente" },
    { icon: <FaTheaterMasks />, path: "/artist", item: "Artista" },
    { icon: <GiDrumKit />, path: "/band", item: "Banda" },
    { icon: <HiOutlineUserGroup />, path: "/role", item: "Função" },
    { icon: <GiGuitarHead />, path: "/instrument", item: "Instrumento" },
    { icon: <BsOpticalAudioFill />, path: "/equipament", item: "Equipamento" },
    { icon: <IoIosMusicalNotes />, path: "/music", item: "Música" },
  ]

  return (
    <div className='bg-gray-900'>
      <div className='flex flex-col w-full h-20 justify-center items-center'>
        <Logo />
      </div>
      <div className='text-yellow-200  min-h-screen'>
        <ul>
          {menuItem.map((item, i) => {
            return (
              <div  key={i} className="hover:bg-yellow-500/60 hover:text-white">
              <li className='flex gap-2 p-2 items-center'>
                <span className=" text-4xl rounded p-2 bg-yellow-400">{item.icon}</span> 
                <Link href={item.path}>{item.item}</Link>
              </li>
              </div>
            )
          })}
        </ul>
      </div>
    </div>
  )
}
