import Image from "next/image"
import Link from "next/link"

export const metadata = {
  title: 'Casarão | Comunidade',
  description: 'Generated by Next.js',
  icons: "/fiveicon.ico"
}


export default function Community() {
  return (
    <div className='min-h-screen'>Comunidade!</div>
  )
}
