import Image from "next/image"
import { Inter } from "@next/font/google"
import Link from "next/link"

import ChildrenTitle from "@/components/children-title/page"
import { VscTools } from "react-icons/vsc"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Casarão | Luthieria",
  description: "Generated by Next.js",
}

export default function Luthier() {
  return (
    <div className='min-h-screen'>
      <ChildrenTitle title='Luthieria' iconName={<VscTools size={54} />} />
    </div>
  )
}
