import Image from "next/image"
import Link from "next/link"

import ChildrenTitle from "@/components/children-title/page"

import { AiFillSound } from "react-icons/ai"

export const metadata = {
  title: "Equipamentos",
  description: "Generated by Next.js",
}

export default function Equipament() {
  return (
    <div className='min-h-screen'>
      <ChildrenTitle title='Equipamentos' iconName={<AiFillSound size={54} />} />
    </div>
  )
}
