import Image from "next/image"
import Link from "next/link"

export const metadata = {
  title: 'Casarão | Luthieria',
  description: 'Generated by Next.js',
}

export default function Instrument() {
  return (
    <div className='text-orange-400 bg-gray-900 min-h-screen'>Instrumentos!</div>
  )
}
