import Image from "next/image"
import Link from "next/link"

import ChildrenTitle from "@/components/children-title/page"
import { ImProfile } from "react-icons/im"

export const metadata = {
  title: "Casarão | Perfil",
  description: "Generated by Next.js",
}

export default function Profile() {
  return (
    <div className='min-h-screen'>
      <ChildrenTitle title='Perfil' iconName={<ImProfile size={54} />} />
    </div>
  )
}
