"use client"

import "../../styles/globals.css"

import { Metadata } from "next"

import { QueryClient, QueryClientProvider } from "@tanstack/react-query"

import { Header } from "@/components/header/page"
import { Footer } from "@/components/footer/page"
import Sidebar from "@/components/sidebar/page"

import { Inter } from "@next/font/google"

// export const metadata: Metadata = {
//   title: "Casarão | Configurações",
//   description: "Generated by Next.js",
// }

const inter = Inter({ subsets: ["latin"] })

const queryClient = new QueryClient()

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='pt-BR'>
      <body className=' bg-gray-900 text-stone-50'>
        <QueryClientProvider client={queryClient}>
          <div className='flex flex-row'>
            <Sidebar />
            <div className='flex flex-col bg-yellow-200 w-full'>
              <Header />
              <div className='px-4'>{children}</div>
            </div>
          </div>
          <Footer />
        </QueryClientProvider>
      </body>
    </html>
  )
}
