"use client"

import { signIn, signOut, useSession } from "next-auth/react"

import { Navbar } from "../navbar/page"
import Profile from "../profile/page"
import Logout from "../logout/page"
import Signin from "../signin/page"
import Settings from "../settings/page"

import { Toaster } from "react-hot-toast"
import SigninButton from "../SigninButton"

export const metadata = {
  title: "mms - casarão",
  description: "Generated by Next.js",
}

export function Header() {
  const { data: session } = useSession()

  return (
    <div className='flex w-full justify-between bg-yellow-300 shadow-gray-800/90 shadow-md p-2'>
      <Navbar />
      <div className='flex gap-2'>
        {session?.user ? (
          <button onClick={() => signIn()}>
            <Profile name='Edmilson' age={25} />
            <Settings />
            <Logout name='Edmilson' age={25} />
          </button>
        ) : (
          <>
            {session?.user}
            <button onClick={() => signIn()}>
              <Signin />
            </button>
            {/* <SigninButton /> */}
          </>
        )}
      </div>
    </div>
  )
}
