// "use client"

import { Navbar } from "../navbar/page"
import Profile from "../profile/page"
import Settings from "../settings/page"

import { Toaster } from "react-hot-toast"

export const metadata = {
  title: "mms - casarão",
  description: "Generated by Next.js",
}

export function Header() {
  return (
    <div className='flex w-full justify-between bg-yellow-300 shadow-gray-800/90 shadow-md p-2'>
      <Navbar />
      <div className='flex gap-2'>
        <Profile name='Edmilson' age={25} />
        <Settings />
      </div>
      <Toaster />
    </div>
  )
}
