import Image from "next/image"
import Link from "next/link"

import ChildrenTitle from "@/components/children-title/page"
import { GiDrumKit } from "react-icons/gi"

export const metadata = {
  title: "Casarão | Luthieria",
  description: "Generated by Next.js",
}

export default function Instrument() {
  return (
    <div className='min-h-screen'>
      <ChildrenTitle title='Instrumentos' iconName={<GiDrumKit size={54} />} />
    </div>
  )
}
