import Image from "next/image"
import Link from "next/link"

export const metadata = {
  title: 'Papéis',
  description: 'Generated by Next.js',
}

export default function Role() {
  return (
    <div className='text-orange-400 bg-gray-900 min-h-screen'>Papel!</div>
  )
}
